"""objections reminders expert access

Revision ID: 7c4f46712c1e
Revises: f4dd9b345f2e
Create Date: 2026-10-06 20:43:22.163345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c4f46712c1e'
down_revision: Union[str, Sequence[str], None] = 'f4dd9b345f2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expert_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expert_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason_ref', sa.String(length=64), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['expert_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_access_expert_id'), 'expert_access', ['expert_id'], unique=False)
    op.create_index(op.f('ix_expert_access_user_id'), 'expert_access', ['user_id'], unique=False)
    op.create_table('expert_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_questions_user_id'), 'expert_questions', ['user_id'], unique=False)
    op.create_table('objections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_ref', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objections_due_at'), 'objections', ['due_at'], unique=False)
    op.create_index(op.f('ix_objections_user_id'), 'objections', ['user_id'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('remind_on', sa.Date(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kind', 'due_date', 'remind_on', 'channel', name='uq_reminders')
    )
    op.create_index(op.f('ix_reminders_remind_on'), 'reminders', ['remind_on'], unique=False)
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    op.add_column('users', sa.Column('email', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('telegram_chat_id', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('push_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'push_token')
    op.drop_column('users', 'telegram_chat_id')
    op.drop_column('users', 'email')
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_remind_on'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_objections_user_id'), table_name='objections')
    op.drop_index(op.f('ix_objections_due_at'), table_name='objections')
    op.drop_table('objections')
    op.drop_index(op.f('ix_expert_questions_user_id'), table_name='expert_questions')
    op.drop_table('expert_questions')
    op.drop_index(op.f('ix_expert_access_user_id'), table_name='expert_access')
    op.drop_index(op.f('ix_expert_access_expert_id'), table_name='expert_access')
    op.drop_table('expert_access')
    # ### end Alembic commands ###
