"""tax summary and config versions

Revision ID: 0f0608f44faf
Revises: 817e1d93ef7e
Create Date: 2026-10-06 20:36:35.809003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f0608f44faf'
down_revision: Union[str, Sequence[str], None] = '817e1d93ef7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_calculations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('income_tiyn', sa.BigInteger(), nullable=False),
    sa.Column('tax_tiyn', sa.BigInteger(), nullable=False),
    sa.Column('config_version', sa.String(length=32), nullable=False),
    sa.Column('config_sha256', sa.String(length=64), nullable=False),
    sa.Column('inputs_hash', sa.String(length=64), nullable=False),
    sa.Column('trace_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_calculations_user_id'), 'tax_calculations', ['user_id'], unique=False)
    op.create_table('tax_config_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('raw_yaml', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'version', name='uq_tax_config_versions')
    )
    op.create_index(op.f('ix_tax_config_versions_year'), 'tax_config_versions', ['year'], unique=False)
    op.add_column('users', sa.Column('declared_income_tiyn', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=16), server_default='client', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'declared_income_tiyn')
    op.drop_index(op.f('ix_tax_config_versions_year'), table_name='tax_config_versions')
    op.drop_table('tax_config_versions')
    op.drop_index(op.f('ix_tax_calculations_user_id'), table_name='tax_calculations')
    op.drop_table('tax_calculations')
    # ### end Alembic commands ###
