"""Начальная схема: пользователи, согласия, сессии, журнал действий, счета,
выписки, операции, ставки маслихатов.

Колонки с ПДн — Text: в них хранится шифртекст salyq.crypto.EncryptedText.

Revision ID: 9e1eddbfc5e1
Revises: 
Create Date: 2026-10-06 03:00:21.456814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e1eddbfc5e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=True),
    sa.Column('object_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_table('auth_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nonce_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nonce_hash')
    )
    op.create_table('region_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_code', sa.String(length=16), nullable=False),
    sa.Column('activity_code', sa.String(length=16), nullable=False),
    sa.Column('rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.CheckConstraint('rate > 0 AND rate < 1', name='ck_region_rates_rate'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_code', 'activity_code', 'valid_from', name='uq_region_rates')
    )
    op.create_index(op.f('ix_region_rates_region_code'), 'region_rates', ['region_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iin', sa.Text(), nullable=False),
    sa.Column('iin_hash', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('region_code', sa.String(length=16), nullable=True),
    sa.Column('activity_code', sa.String(length=16), nullable=True),
    sa.Column('ip_registered_on', sa.Date(), nullable=True),
    sa.Column('employees_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('employees_count >= 0', name='ck_users_employees'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iin_hash', name='uq_users_iin_hash')
    )
    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bank', sa.String(length=32), nullable=False),
    sa.Column('iban', sa.Text(), nullable=False),
    sa.Column('iban_masked', sa.String(length=16), nullable=False),
    sa.Column('iban_hash', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'bank', 'iban_hash', name='uq_bank_accounts_iban')
    )
    op.create_index(op.f('ix_bank_accounts_user_id'), 'bank_accounts', ['user_id'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("type IN ('pd_processing', 'automated_processing', 'cross_border')", name='ck_consents_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_user_id'), 'consents', ['user_id'], unique=False)
    op.create_table('statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('file_ref', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('period_from', sa.Date(), nullable=True),
    sa.Column('period_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rows_parsed', sa.Integer(), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=False),
    sa.Column('rows_duplicate', sa.Integer(), nullable=False),
    sa.Column('rows_skipped', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statements_account_id'), 'statements', ['account_id'], unique=False)
    op.create_index(op.f('ix_statements_file_sha256'), 'statements', ['file_sha256'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount_tiyn', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('counterparty', sa.Text(), nullable=False),
    sa.Column('counterparty_id', sa.Text(), nullable=False),
    sa.Column('counterparty_account', sa.Text(), nullable=False),
    sa.Column('counterparty_hash', sa.String(length=64), nullable=False),
    sa.Column('knp', sa.String(length=3), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('operation', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('confirmed_by_user', sa.Boolean(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.CheckConstraint("direction IN ('in', 'out')", name='ck_transactions_direction'),
    sa.CheckConstraint('amount_tiyn > 0', name='ck_transactions_amount_positive'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='ck_transactions_confidence'),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'fingerprint', name='uq_transactions_fingerprint')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_counterparty_hash'), 'transactions', ['counterparty_hash'], unique=False)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    # ### end Alembic commands ###

    # Журнал действий — только добавление (ТЗ 2: внутренний контроль)
    op.execute("""
        CREATE FUNCTION audit_log_append_only() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit_log: изменение и удаление записей запрещены';
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER audit_log_append_only
        BEFORE UPDATE OR DELETE OR TRUNCATE ON audit_log
        FOR EACH STATEMENT EXECUTE FUNCTION audit_log_append_only();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS audit_log_append_only ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS audit_log_append_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_counterparty_hash'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_statements_file_sha256'), table_name='statements')
    op.drop_index(op.f('ix_statements_account_id'), table_name='statements')
    op.drop_table('statements')
    op.drop_index(op.f('ix_consents_user_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_bank_accounts_user_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_table('users')
    op.drop_index(op.f('ix_region_rates_region_code'), table_name='region_rates')
    op.drop_table('region_rates')
    op.drop_table('auth_challenges')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
