"""categorization and fx

Revision ID: 817e1d93ef7e
Revises: 9e1eddbfc5e1
Create Date: 2026-10-06 20:33:50.161111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '817e1d93ef7e'
down_revision: Union[str, Sequence[str], None] = '9e1eddbfc5e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency', 'rate_date', name='uq_fx_rates')
    )
    op.create_table('categorization_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('counterparty_hash', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'counterparty_hash', 'direction', name='uq_categorization_rules')
    )
    op.create_index(op.f('ix_categorization_rules_user_id'), 'categorization_rules', ['user_id'], unique=False)
    op.add_column('transactions', sa.Column('category_source', sa.String(length=64), nullable=True))
    op.add_column('transactions', sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('transactions', sa.Column('region_code', sa.String(length=16), nullable=True))
    op.add_column('transactions', sa.Column('amount_kzt_tiyn', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'amount_kzt_tiyn')
    op.drop_column('transactions', 'region_code')
    op.drop_column('transactions', 'confirmed_at')
    op.drop_column('transactions', 'category_source')
    op.drop_index(op.f('ix_categorization_rules_user_id'), table_name='categorization_rules')
    op.drop_table('categorization_rules')
    op.drop_table('fx_rates')
    # ### end Alembic commands ###
